language: android
sudo: required
jdk: oraclejdk8

# Cache gradle dependencies only
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

env:
  global:
  - ANDROID_API=25
  - EMULATOR_API=21
  - ANDROID_BUILD_TOOLS=25.0.0
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=5
  # Encrypted store password
  - secure: "peLr2bCeoZwoEufrfO3zDTCSoKRSC/IeyUs3YecjTZgZwR+IRztUAy9TikaTha3+XaiNANFy47STjo6HLFSo402ea/UsOIrrSjlUeUKbWJr3RRe8Zoaa75n9n2jwUWYu5ZJ2u9FDEwSzFH3E8KeB/wg8Kz6tucyAIYAQpqLLS61mwZ1yvQHZF6zB77sdY1jygkBCYG2pzHUy9wggu0Pj9xEy0zbKdJTzdL6kAbc9wP1qcT7dywvls8Fuob800nnRoL/jRgqOyol+VdzC6PMDXr6HAgtY6CLpO135TP6Xe/vs2Xrc1uq5OIgYNKfbsf+8LONQum0NRtMN4W8c1cGZknFLv/xfakb2LVoDeU5De/Hs/90M1LIasZ9lrT5e8+BAcpI/uqFBgBOS6Cv+ra686aj2V9PEIo3IAVarGbXcQcg8M72oq/BPNl6Qn+MIKIsTcRrer0yzGGYtz/AXJpbD8YMjU1zqJzzRaQgFI5Br3Un8izvN7m1oatvKXDkw5CPgYsyPUbOgSn6A2+6MUr/orqcuHOimS1R/P2G+vKzmaO8LRPwGZ00Bj7JR/qWCP1fYWB6jV7uAIJ2URM/Inus9zOhhnUNnkfDHEzLfVbGRyvd8GVbG+kxJ5suOZ2YupW/GtJNHtzhwOL6mdWLRtNHcOSFleGml4zHE4hCUQNMi5EA="
  # Encrypted key password
  - secure: "EJyJQdEISNsAj3Gcv+0UPLzWogZBV68agwy8rNj3CVcQ88hetR2sGOhbYmYrf31NK/hs2rKSIc6XYfC1/WI17Qy0HGYx9P4jzJzi0tVmyVeiJX0XRn3lnfYJU+QB4u85yOv1AsT10QJbxbwkmLGCMk2T6DTTJ7+dOgQEZFlFWAo8cX/rGWmafxME04tTn7fdQHXTCGj8R9+THT08npQ2rImTXIOCZyRlt+9GGXGP0qL+HmyDstLTRc4tOvU9Dtf22R5dccdtpkSBLPdC+BR5NLpLvMAavepHYI9L6KkSInWzOarGlLMKFG3ekAT3YZC1Wr0MP0z6OFgDlNJpbF25UMG9exrDq/im6e6MtTXcXOVCx8BR1s9Sme3ta42X6MW48Qn8rgXWglNjhdYnUVKnO7cznwXdgcXMOQFsIyBGnEuyiRP5q6swEBs+bn1R49oQHraEp3Z1ott74FRexi01Qx6ck0dJyf9gGzX22nT8o4t1i/i7rdIocyMs5jcwoZ6I0CtDx8bpQMDtZd20lnqMQLsWc/MszC7kR3gW7JutBdcASgDtZimopud4luQ1ze4eitdd/up20yKxRt+4aNQ1XpL3lNLvC2MA48uSlXZdWyLtnvHS4rfvpMLEOORfxngfRSa+AZgzx2MSGxcQjDw2UA0b3fVLE3eGrBUYoz6bKgU="

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository # For design library
  - addon-google_apis-google-19 # Google play services
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
- cd SampleWebApp # Navigate to project root
- openssl aes-256-cbc -K $encrypted_d948bd61ff82_key -iv $encrypted_d948bd61ff82_iv -in keystore.jks.enc -out keystore.jks -d # Use the encrypted keystore

before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
  - ./gradlew test -PdisablePreDex --stacktrace
  - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace

# before_deploy:
# - cp $TRAVIS_BUILD_DIR/SampleWebApp/keystore.jks $HOME
# #- cp $TRAVIS_BUILD_DIR/.keystore $HOME
# #- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 $HOME/android/release-unsigned.apk SampleWebApp -keystore $HOME/.keystore -storepass $storepass -keypass $keypass
# - cd app/build/outputs/apk/
# - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 app-release-unsigned.apk SampleWebApp -keystore $HOME/keystore.jks -storepass $storepass -keypass $keypass
# # Verification
# - jarsigner -verify app-release-unsigned.apk
# - "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-release-unsigned.apk SampleWebApp.apk"
# #- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign 4 $HOME/android/release-unsigned.apk $HOME/android/SampleWebApp.apk"

# deploy:
#   provider: releases
#   file: SampleWebApp.apk
#   skip_cleanup: true

#   on:
#     repo: abagg35/a35-waterguru-android
#     #tags: true
#     jdk: oraclejdk8

#   api_key:
#     secure: "e62065c38e45b94a3497e9189805ce4ae1156b33"